name: Build and Deploy to Production

on:
  push:
    branches: ["working-app-tested", "main"]
  pull_request:
    branches: ["working-app-tested", "main"]

jobs:
  build-and-push-dockerfile-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.DOCKERHUB_USERNAME }}/fee-management-app
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=sha

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64,linux/arm64
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Trigger Dokploy Deployment
        if: github.ref == 'refs/heads/working-app-tested' || github.ref == 'refs/heads/main'
        run: |
          curl -X 'POST' \
          'https://${{ secrets.DOKPLOY_DOMAIN }}/api/trpc/application.deploy' \
          -H 'accept: application/json' \
          -H 'x-api-key: ${{ secrets.DOKPLOY_API_KEY }}' \
          -H 'Content-Type: application/json' \
          -d '{
              "json":{
                  "applicationId": "${{ secrets.DOKPLOY_APP_ID }}"
              }
          }' 